-- 001_init.sql
-- Self-hostable schema with local auth built into public.profiles
-- No Supabase auth dependency. No public.users table. No public.user_profiles table.

BEGIN;

-- Needed for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Optional but nice for username/email case-insensitive comparisons:
-- (If you don't want extensions beyond pgcrypto, delete these lines.)
-- CREATE EXTENSION IF NOT EXISTS citext;

-- PROFILES (single source of truth for auth + profile + stats)
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Auth
    email text UNIQUE,
    password_hash text NOT NULL,

    -- Identity
    username text UNIQUE NOT NULL,
    displayname text NOT NULL,
    role text NOT NULL DEFAULT 'default',

    -- Cosmetic (previously user_profiles)
    color text NOT NULL DEFAULT '#3b82f6',
    text_color text NOT NULL DEFAULT '#ffffff',

    -- Stats / misc
    tokens integer NOT NULL DEFAULT 0,
    bio text,
    boards_generated integer NOT NULL DEFAULT 0,
    games_finished integer NOT NULL DEFAULT 0,
    money_won integer NOT NULL DEFAULT 0,
    games_won integer NOT NULL DEFAULT 0,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    -- Optional: enforce lowercase username/email at the DB level.
    -- If you prefer to normalize in code only, remove these.
    CONSTRAINT profiles_username_lower_chk CHECK (username = lower(username)),
    CONSTRAINT profiles_email_lower_chk CHECK (email = lower(email))
    );

-- Keep updated_at fresh
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- JEOPARDY_BOARDS
CREATE TABLE IF NOT EXISTS public.jeopardy_boards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner uuid,
    board jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
    );

ALTER TABLE ONLY public.jeopardy_boards
    ADD CONSTRAINT jeopardy_boards_owner_fkey
    FOREIGN KEY (owner) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- IMAGE_ASSETS
CREATE TABLE IF NOT EXISTS public.image_assets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    storage_key text NOT NULL,
    sha256 text NOT NULL UNIQUE,
    content_type text NOT NULL DEFAULT 'image/webp',
    bytes integer,
    width integer,
    height integer,
    source_url text,
    license text,
    attribution text,
    created_at timestamptz NOT NULL DEFAULT now()
    );

CREATE INDEX IF NOT EXISTS image_assets_created_at_idx
    ON public.image_assets USING btree (created_at DESC);

-- TTS_ASSETS
CREATE TABLE IF NOT EXISTS public.tts_assets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sha256 text NOT NULL UNIQUE,
    storage_key text NOT NULL,
    content_type text NOT NULL DEFAULT 'audio/mpeg',
    bytes integer,
    text text NOT NULL,
    text_type text NOT NULL DEFAULT 'text',
    voice_id text NOT NULL DEFAULT 'Matthew',
    engine text NOT NULL DEFAULT 'standard',
    language_code text,
    created_at timestamptz NOT NULL DEFAULT now()
    );

CREATE INDEX IF NOT EXISTS tts_assets_created_at_idx
    ON public.tts_assets USING btree (created_at DESC);

-- Helper: username availability
CREATE OR REPLACE FUNCTION public.is_username_taken(candidate text)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
SELECT exists (
    SELECT 1
    FROM public.profiles
    WHERE username = lower(trim(candidate))
);
$$;

COMMIT;
