export const MODIFIERS = [
  "History of",
  "Origins of",
  "Early Days of",
  "Modern Era of",
  "Rise of",
  "Fall of",
  "Foundations of",
  "Basics of",
  "Core Concepts of",
  "Legends of",
  "Icons of",
  "Giants of",
  "Masters of",
  "Pioneers of",
  "Leaders in",
  "Champions of",
  "Movements in",
  "Schools of",
  "Styles of",
  "Trends in",
  "Forces Behind",
  "Power Players in",
  "Game-Changers in",
  "Behind the Scenes of",
  "Anatomy of",
  "Structure of",
  "Evolution of",
  "Timeline of",
  "Golden Age of",
  "Dark Side of",
  "Wonders of",
  "Mysteries of",
  "Rivalries in",
  "Battles in",
  "Expansion of",
  "Collapse of",
  "Systems of",
  "Theory of",
  "Art of",
  "Science of",
  "Politics of",
  "Culture of",
  "Economics of",
  "Geography of",
  "Key Moments in",
  "Major Events in",
  "Turning Points in",
  "Milestones in",
  "Breakthroughs in",
  "Discoveries in",
  "Inventions in",
  "Innovations in",
  "Failures of",
  "Mistakes of",
  "Controversies in",
  "Debates in",
  "Secrets of",
  "Hidden Side of",
  "Lesser-Known Facts About",
  "Strange Facts About",
  "Famous Figures in",
  "Influential People in",
  "Great Works of",
  "Defining Moments in",
  "Firsts of",
  "Records of",
  "Extremes of",
  "Oddities of",
];

export const BLOCKED: Record<string, string[]> = {
  // ===== FAILURE / NEGATIVE MODIFIERS =====
  "Failures of": [
    "World Capitals",
    "Capital Cities",
    "Time Zones",
    "Measurement Systems",
    "Currencies",
    "Flags",
    "National Anthems",
    "Writing Systems",
    "Symbols",
    "Periodic Table",
  ],

  "Mistakes of": [
    "World Capitals",
    "Capital Cities",
    "Time Zones",
    "Measurement Systems",
    "Currencies",
    "Flags",
    "National Anthems",
    "Writing Systems",
    "Symbols",
    "Periodic Table",
  ],

  "Dark Side of": [
    "World Capitals",
    "Capital Cities",
    "Measurement Systems",
    "Time Zones",
    "Currencies",
    "National Anthems",
    "Writing Systems",
    "Periodic Table",
  ],

  "Collapse of": [
    "World Capitals",
    "Capital Cities",
    "Measurement Systems",
    "Time Zones",
    "Currencies",
    "Flags",
  ],

  // ===== CONTROVERSY / DEBATE =====
  "Controversies in": [
    "World Capitals",
    "Capital Cities",
    "Mountain Ranges",
    "Oceans and Seas",
    "Time Zones",
    "Flags",
    "National Anthems",
    "Measurement Systems",
  ],

  "Debates in": [
    "World Capitals",
    "Capital Cities",
    "Mountain Ranges",
    "Oceans and Seas",
    "Flags",
    "National Anthems",
    "Time Zones",
  ],

  // ===== INVENTION / INNOVATION =====
  "Inventions in": [
    "Ancient Egypt",
    "Roman Empire",
    "World War I",
    "World War II",
    "The Cold War",
    "The Crusades",
    "Feudal Japan",
  ],

  "Innovations in": [
    "World Capitals",
    "Capital Cities",
    "Mountain Ranges",
    "Major Rivers",
    "Oceans and Seas",
    "Deserts",
    "Rainforests",
  ],

  // ===== PEOPLE-FOCUSED =====
  "Famous Figures in": [
    "Algorithms",
    "Data Structures",
    "Measurement Systems",
    "Time Zones",
    "Currencies",
    "Music Theory",
    "Logic",
    "Ethics",
  ],

  "Influential People in": [
    "Algorithms",
    "Data Structures",
    "Measurement Systems",
    "Time Zones",
    "Currencies",
    "Music Theory",
    "Logic",
    "Ethics",
  ],

  // ===== STRUCTURAL / ABSTRACT MODIFIERS =====
  "Structure of": ["Pop Music", "Hit Songs", "Celebrity Culture", "Memes", "Influencers"],

  "Theory of": [
    "Pop Music",
    "Hit Songs",
    "Famous Bands",
    "Celebrity Culture",
    "Memes",
    "Boy Bands",
    "Girl Groups",
  ],

  "Systems of": ["Pop Music", "Hit Songs", "Celebrity Culture", "Memes", "Famous Actors"],

  // ===== RECORD / EXTREME =====
  "Records of": ["Ethics", "Logic", "Philosophy", "Political Philosophy", "Music Theory"],

  "Extremes of": ["Ethics", "Logic", "Political Philosophy", "Music Theory"],

  // ===== SECRET / ODD =====
  "Secrets of": [
    "World Capitals",
    "Capital Cities",
    "Measurement Systems",
    "Time Zones",
    "Currencies",
    "National Anthems",
  ],

  "Oddities of": ["Ethics", "Logic", "Political Philosophy", "Music Theory"],

  // ===== ERA-SPECIFIC MODIFIERS =====
  "Golden Age of": [
    "Algorithms",
    "Data Structures",
    "Measurement Systems",
    "Time Zones",
    "Currencies",
  ],

  "Modern Era of": ["Ancient Egypt", "Mesopotamia", "Indus Valley Civilization"],
};
