export const SUBJECTS = [
    // ===== HISTORY =====
    'Ancient Egypt',
    'Mesopotamia',
    'Indus Valley Civilization',
    'Ancient Greece',
    'Roman Empire',
    'Byzantine Empire',
    'Ottoman Empire',
    'Mongol Empire',
    'Holy Roman Empire',
    'Viking Age',
    'Medieval Europe',
    'Feudal Japan',
    'Samurai Culture',
    'Chinese Dynasties',
    'The Crusades',
    'The Renaissance',
    'The Reformation',
    'Age of Exploration',
    'Colonial America',
    'American Revolution',
    'French Revolution',
    'Napoleonic Wars',
    'Industrial Revolution',
    'Victorian Era',
    'World War I',
    'World War II',
    'The Cold War',
    'The Space Race',
    'The Vietnam War',
    'The Korean War',
    'The Civil Rights Movement',
    'Women’s Suffrage',
    'The Great Depression',
    'The New Deal',
    'Fall of the Berlin Wall',
    'The Soviet Union',
    'Modern Europe',
    'Modern China',

    // ===== GEOGRAPHY =====
    'World Capitals',
    'Capital Cities',
    'Mountain Ranges',
    'Volcanoes',
    'Active Volcanoes',
    'Earthquakes',
    'Major Rivers',
    'Longest Rivers',
    'Largest Lakes',
    'Oceans and Seas',
    'Island Nations',
    'Archipelagos',
    'Peninsulas',
    'Straits',
    'Canals',
    'Deserts',
    'Rainforests',
    'National Parks',
    'UNESCO World Heritage Sites',
    'Famous Landmarks',
    'Ancient Cities',
    'Modern Megacities',
    'Border Disputes',
    'Time Zones',
    'Polar Regions',
    'Arctic Exploration',
    'Antarctica',
    'Extreme Environments',

    // ===== SCIENCE =====
    'Astronomy',
    'Astrophysics',
    'Cosmology',
    'Planetary Science',
    'The Solar System',
    'Exoplanets',
    'Stars',
    'Black Holes',
    'Physics',
    'Quantum Mechanics',
    'Relativity',
    'Thermodynamics',
    'Chemistry',
    'Organic Chemistry',
    'Biochemistry',
    'Periodic Table',
    'Biology',
    'Genetics',
    'Evolution',
    'Microbiology',
    'Virology',
    'Human Anatomy',
    'Neuroscience',
    'Psychology',
    'Cognitive Science',
    'Ecology',
    'Climate Science',
    'Meteorology',
    'Oceanography',
    'Geology',
    'Plate Tectonics',
    'Paleontology',
    'Extinct Species',

    // ===== TECHNOLOGY =====
    'Computing',
    'Computer Science',
    'Algorithms',
    'Data Structures',
    'Programming Languages',
    'Web Development',
    'Mobile Apps',
    'Cybersecurity',
    'Cryptography',
    'Artificial Intelligence',
    'Machine Learning',
    'Neural Networks',
    'Robotics',
    'Automation',
    'Quantum Computing',
    'Cloud Computing',
    'Internet History',
    'Social Media',
    'Video Games',
    'Game Consoles',
    'Operating Systems',
    'Open Source Software',
    'Hardware Design',
    'Semiconductors',
    'Microprocessors',
    'Space Technology',
    'Rocketry',
    'Satellites',

    // ===== ARTS & LITERATURE =====
    'Classic Literature',
    'World Literature',
    'Poetry',
    'Epic Poems',
    'Shakespeare Plays',
    'Greek Mythology',
    'Roman Mythology',
    'Norse Mythology',
    'World Mythology',
    'Folklore',
    'Fairy Tales',
    'Philosophy',
    'Ethics',
    'Logic',
    'Political Philosophy',
    'Art History',
    'Renaissance Art',
    'Modern Art',
    'Impressionism',
    'Surrealism',
    'Architecture',
    'Architectural Styles',

    // ===== MUSIC & ENTERTAINMENT =====
    'Classical Music',
    'Classical Composers',
    'Opera',
    'Jazz',
    'Blues',
    'Rock Music',
    'Hip Hop',
    'Pop Music',
    'Film Music',
    'Movie Soundtracks',
    'Broadway Musicals',
    'Famous Bands',
    'Concept Albums',
    'Music Theory',
    'Film History',
    'Silent Films',
    'Classic Hollywood',
    'Foreign Films',
    'Film Directors',
    'Television History',

    // ===== FOOD, CULTURE, MISC =====
    'World Cuisines',
    'Regional Foods',
    'Spices',
    'Cooking Techniques',
    'Beverages',
    'Wine',
    'Beer',
    'Coffee',
    'Tea',
    'Cultural Traditions',
    'Holidays',
    'Rituals',
    'Languages',
    'Writing Systems',
    'Etymology',
    'Symbols',
    'Flags',
    'National Anthems',
    'Currencies',
    'Measurement Systems',

    // ===== POP CULTURE =====
    'Popular Movies',
    'Movie Franchises',
    'Superhero Movies',
    'Animated Films',
    'Science Fiction Films',
    'Fantasy Films',
    'Classic Films',
    'Cult Movies',
    'Film Characters',
    'Famous Actors',
    'Famous Actresses',
    'Film Directors',

    'Television Shows',
    'Streaming Series',
    'Sitcoms',
    'Drama Series',
    'Science Fiction TV',
    'Fantasy TV',
    'Reality Television',
    'TV Characters',
    'TV Spin-Offs',
    'Final Episodes',

    'Pop Music',
    'Hit Songs',
    'Music Charts',
    'Music Awards',
    'Famous Singers',
    'Pop Stars',
    'Boy Bands',
    'Girl Groups',
    'Album Titles',
    'Song Lyrics',

    'Celebrity Culture',
    'Celebrity Couples',
    'Celebrity Scandals',
    'Famous Feuds',
    'Red Carpet Moments',

    'Internet Culture',
    'Viral Videos',
    'Memes',
    'Social Media Trends',
    'Influencers',
    'Online Communities',

    'Comic Books',
    'Graphic Novels',
    'Superheroes',
    'Supervillains',
    'Comic Book Publishers',

    // ===== GAMING =====
    'Video Game Franchises',
    'Classic Video Games',
    'Retro Games',
    'Arcade Games',
    'Role-Playing Games',
    'Strategy Games',
    'First-Person Shooters',
    'Indie Games',
    'Mobile Games',
    'Game Characters',
    'Game Worlds',
    'Video Game Consoles',
    'Game Developers',
    'Esports',
];
